export const map = {
    'Drifting Phantoms': 'phantom-tag',
    'Dusk Dwellers': 'dweller-tag',
    'Lightning Blitz': 'blitz-tag',
    'Frostborns': 'frost-tag',
    "Nature's Relics": 'relic-tag',
    'Rising Talons': 'talon-tag',
    'Depth Striders': 'strider-tag',
    'Guardians': 'guardian-tag',
    "Observers": 'observer-tag',
    'Pyro Hazards': 'pyro-tag',
    'Primal Fang': 'primal-tag',
    'Stonebounds': 'stonebound-tag',
    'Biohazards': 'bio-tag',
    'Vanguard': 'vanguard-tag',
    'Velvet Grace': 'grace-tag',
    'Ascendants': 'ascendant-tag',
    "Author's Choice": 'fav-tag',
    'Glitchborn': 'glitch-tag',
    'Forged': 'forge-tag',
    'Lab Rat': 'lab-tag'
}